### ISSUE TITLE
Conflict with MultiplayerHLAPI

### ISSUE THREAD

**Issue by skaughtx0r** [ehakram/FrameRateBooster#1]
It seems this conflicts with the MultiplayerHLAPI package. There may also be other Unity packages that conflict due to a `Mono.Cecil` package that gets added.

The way I figured out how to fix this is to Remove the Mono.Cecil dll's from FrameRateBooster and instead use the ones provided via package manager by creating an asmdef in the Optimizer.cs Editor folder.

In the asmdef, you need to enable `Override References` and add `Mono.Cecil.dll` as an `Assembly Reference`.

```
"overrideReferences": true,
"precompiledReferences": [
    "Mono.Cecil.dll"
]
```

The README would need to be update to say that you must install the `Mono Cecil` (nuget.mono-cecil) package.

Would you like me to submit a PR for this?

**Comment by tool-buddy** [comment]
Hi
Thanks for reporting this.
Last time I checked this issue, I found that MPHLAPI was referencing a Mono.Cecil dll it gets from a package from Unity's package manager, but said package was not available to the public. If it was, then it would have solved the issue in a very nice way, since I could reference the same package.
Now, just to be sure I understood what you said: is the Mono.Cecil.dll you are speaking about coming from Unity's package manager or from VS's Nuget pcakge manager? If it is from Unity's package manager, I could not find it. Can you please tell me how to get it?
Thanks

**Comment by skaughtx0r** [comment]
It is still a package _intended_ for internal use: https://docs.unity3d.com/Packages/com.unity.nuget.mono-cecil@1.0/manual/index.html

However, you can just manually add the following to the manifest.json:

```json
{
    "nuget.mono-cecil": "0.1.6-preview"
}
```

If this was setup as a UPM package, you could list it as a dependency. I played around with trying to get FRB to work as a UPM package, but ran into problems with the assembly not getting created or not being created in the right order.

**Comment by tool-buddy** [comment]
Thanks for the explanation. Your PR is welcomed. I will not include this change in the Asset Store version of the asset until I find a way to add the package automatically from code. Having an asset not building out of the box, even if everything is explained in the ReadMe/asset description, is a sure way to get 1 star reviews.

**Comment by skaughtx0r** [comment]
While I do agree, it currently does not build out of the box if you have any UPM packages installed that include the `nuget.mono-cecil` package.

I think part of the issue can be alleviated by including an `asmdef` for the `Editor/Optimizer.cs` that lists the Mono.Cecil reference (see original post). This way, if the `nuget.mono-cecil` package is installed, you could just _not_ import the Mono.Cecil libs included in this asset, and then everything should "just work".

**Comment by tool-buddy** [comment]
Thanks for the explanation. Please submit the PR and I will take a look at this in the upcoming days.

**Comment by tool-buddy** [comment]
@skaughtx0r I tried a solution to automatically add the package, using the Package Manager's API, so that users don't have to do a thing. Unfortunately, it is not working reliably. The WIP is available here:
https://github.com/ehakram/FrameRateBooster/tree/WIP_Mono.Cecil_Conflict

I explain (and ask for help) what is not satisfying with this solution here (in the publishers unity forum):
https://forum.unity.com/threads/what-is-the-best-way-to-automatically-install-needed-packages.1083362/

If you don't have access to it, here is the main part:

1. - When a user imports my assets, and thanks to how I setup the assembly definitions, the importer will build first, then the rest of the code that needs the package will build second. That second part will always fail since the package is missing. So the users will get build errors for a moment.
2. - The Client.Add is called too often. I wanted to use the result of Client.Search to see if the asset is already installed in this project before trying to add it, but I can't find how. Neither SearchRequest.Result.resolvedPath nor SearchRequest.Result.resolvedPath.status seem to be a reliable way to get that information
3. - Sometimes, the compiler errors from code needing the package stop the execution of Installer. Some other times, it does not.

It all boils down to this: how to reliably execute some editor code when there are compiler errors.
Any input is welcome.

**Comment by tool-buddy** [comment]
In the end, I just replaced usage of a mono.cecil dll with its source code. This does not lead to conflicts with nuget.mono-cecil package.
Fixed in commit acb03697ab76f0250e704b422f10f3c482f78eaf

**Comment by skaughtx0r** [comment]
Thanks, sorry I didn't get back to you sooner to look at your earlier changes. I'll try out your latest commit when I get a chance.

**Comment by tool-buddy** [comment]
No worries. Take your time
